project:
  type: website
  output-dir: docs
website:
  announcement: 
    icon: megaphone
    dismissable: true
    content: "**Alert** Hello Class! We are half way through the semester! I hope you guys are enjoying the course "
    type: primary
    position: below-navbar
  page-navigation: true
  page-footer:
    background: "#343a40"
    right: "Created by Dr.B and Venkata Surya Vineel Nekkanti to enhance your learning"
    left: "&copy; Copyright 2024, Dr. B"
  favicon: "images/logo_2.png"
    
  navbar:
    background: "#343a40"
    #logo: "images/nav_bar_logo.png"
    title: "FALL 2024: Predective Business Analytics using R by Dr. B"
    align: centre
    search: false
    collapse-below: lg
    right:
        - href: course-overview.qmd
          text: Course Overview
        - href: index.qmd
          text: Faculty
        - href: "https://www.google.com/"
          target: "_blank"
          text: Syllabus
        - href: "https://www.google.com/"
          target: "_blank"
          text: Schedule          
        - href: challenges_winner_template.qmd
          text: "The Challenges Hall of Fame"
        - href: useful-links.qmd
          text: Useful Links
    tools:
        - icon: backpack-fill
          text: "Blackboard"
          url: https://webcourses.niu.edu/ultra/courses/_348339_1/outline
          target: "_blank"
  sidebar:
    background: "#343a40" 
    logo: "images/course_images/logo2.jpg"
    pinned: true
    align: centre
    style: docked
    search: true
    contents:
    - section: "Material"
      contents:
      - href: weekly_cc_1.qmd
        text: "Week 1"
      - href: coming-soon.qmd
        text: "Week 2"

    - section: "Class Links"
      contents:
      - href: in_class.qmd
        text: "Week 1"
      - href: https://www.google.com/
        text: "Week 2"

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: true
    code-copy: true
    code-overflow: wrap
    code-link: true
    #css: styles.css
    grid:
      body-width: 1000px
      margin-width: 250px    
  
execute:
  freeze: auto

editor: visual