project:
  type: website
  output-dir: docs
website:
  announcement: 
    icon: megaphone
    dismissable: true
    content: "Hello Class! We are half way through the semester! I hope you guys are enjoying the course -**Dr.B** "
    type: primary
    position: below-navbar
  page-navigation: true
  page-footer:
    background: "#343a40"
    right: "Created by Dr.B and Venkata to enhance your learning"
    left: "&copy; Copyright 2024, Dr. B"
  favicon: "images/logo_2.png"
    
  navbar:
    background: "#343a40"
    #logo: "images/nav_bar_logo.png"
    title: "FALL 2024: OMIS-482 by Dr. B"
    align: centre
    search: false
    collapse-below: lg
    right:
        - href: course-overview.qmd
          text: Course Overview
        - href: index.qmd
          text: Faculty
        - href: "https://omis482syllabusfall2024.netlify.app/"
          text: Syllabus
        - href: "https://omis482syllabusfall2024.netlify.app/schedule.html"
          text: Schedule          
        - href: student-dashboard.qmd
          text: Dr.B Learning Leaderboard
        - href: challenges_winner_template.qmd
          text: "The Challenges Hall of Fame"
        - href: useful-links.qmd
          text: Useful Links
    tools:
        - icon: backpack-fill
          text: "Blackboard"
          url: https://webcourses.niu.edu/ultra/courses/_348339_1/outline
          target: "_blank"
  sidebar:
    background: "#343a40" 
    logo: "images/course_images/logo2.jpg"
    pinned: true
    align: centre
    style: docked
    search: true
    contents:
    - section: "Course Chapters"
      contents:
      - href: https://chapter0-book-482.netlify.app/chapter0.html
        text: "Chapter 0"
      - href: https://chapter1-book-482.netlify.app/chapter1.html
        text: "Chapter 1"
      - href:  https://chapter2-book-482.netlify.app/chapter2.html
        text: "Chapter 2"
    - section: "In-class Materials"
      contents:
      - href: https://omis482-week1-teaching-materials.netlify.app/
        text: "Week 1"
      - href: https://omis482-week2-teaching-materials.netlify.app/
        text: "Week 2"
      - href: https://omis482-week3-teaching-materials.netlify.app/
        text: "Week 3"
      - href: https://omis482-week4-teaching-materials.netlify.app/
        text: "Week 4"
      - href: https://omis482-week5-teaching-materials.netlify.app/
        text: "Week 5"  
      - href: https://omis482-week8-teaching-materials.netlify.app/
        text: "Week 8"      
      - href: https://omis482-week10-teaching-materials.netlify.app/
        text: "Week 10" 
    - section: "Coding Checkups"
      contents:
      - href: https://weekly-coding-checkups.netlify.app/wcc1.html
        text: "Week 1"
      - href: https://weekly-coding-checkups.netlify.app/wcc2.html
        text: "Week 2"
      - href: https://weekly-coding-checkups.netlify.app/wcc3.html
        text: "Week 3"
      - href: https://weekly-coding-checkups.netlify.app/wcc4.html
        text: "Week 4"  
      - href: https://weekly-coding-checkups.netlify.app/wcc5.html
        text: "Week 5"
      - href: https://weekly-coding-checkups.netlify.app/wcc9.html
        text: "Week 9"  
      - href: coming-soon.qmd
        text: "Week 10"        
#    - section: "R Challenges"
#      contents:
#      - href: coming-soon.qmd
#        text: Challenge 1


format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: true
    code-copy: true
    code-overflow: wrap
    code-link: true
    #css: styles.css
    grid:
      body-width: 1000px
      margin-width: 250px    
  
execute:
  freeze: auto

editor: visual