---
title: "Useful links"
---


## Install R and RStudio

Download and install R: <https://cran.r-project.org/>

Download and install RStudio: <https://posit.co/download/rstudio-desktop/>

## About R Packages

| Package            | Source                                                              |
|----------------------|--------------------------------------------------|
| Data Manipulation  | [dplyr.tidyverse.org](https://dplyr.tidyverse.org/)                 |
| Data Visualization | [ggplot2.tidyverse.org](https://ggplot2.tidyverse.org/)             |
| Data Modeling      | [www.tidymodels.org/packages](https://www.tidymodels.org/packages/) |

## Cheat Sheets

-   RStudio IDE Cheatsheet: <https://rstudio.github.io/cheatsheets/rstudio-ide.pdf>

-   Data transformation with dplyr Cheatsheet: <https://rstudio.github.io/cheatsheets/data-transformation.pdf>

-   Data Visualization with ggplot2: <https://rstudio.github.io/cheatsheets/data-visualization.pdf>

## Office Hours

| Instructor         | Booking URL                                                                                             |
|--------------------|----------------------------------------------------|
| Dr. B &/or Venkata | [Book Here](https://outlook.office365.com/book/Officedu/?ae=true&login_hint) |

::: callout-note
## Note

When booking office hours, double-check the name of the staff member you want to book the office hours with using the “Select Staff” drop down. Moreover, please keep in mind that the default office hours format is virtual (MS Teams meeting). If you prefer to meet in person, please check with us our in-person availability before booking.
:::
